[workspace]
resolver = "2"
members = [
	"alma-armas",
	"dana-zane",
	"deal-lilim",
	#"deal-lilim-base-sdk",
]
[workspace.dependencies]
matrix-sdk = { version = "0.7.1", default-features = false, features = ["rustls-tls", "anyhow", "e2e-encryption", "sqlite"] }
reqwest = { version = "0.11.24", default-features = false, features = ["json", "rustls-tls"] }
tokio = { version = "1.36.0", default-features = false, features = ["rt", "rt-multi-thread"] }
serde_json = "1.0.114"
serde = { version = "1.0.197", default-features = false, features = ["derive"] }
